# BoT-SORT — YOLO hattı (ReID AKTİF)
# Net bounding box'lar için appearance özelliği faydalıdır.

tracker_type: botsort

track_high_thresh: 0.25
track_low_thresh: 0.1
new_track_thresh: 0.25
track_buffer: 30
match_thresh: 0.8
fuse_score: true

gmc_method: sparseOptFlow

# YOLO kutuları için ReID açık
with_reid: true
proximity_thresh: 0.5
appearance_thresh: 0.25
model: auto
